### ISSUE TITLE
NitroType API 404s

### ISSUE THREAD

**Issue by Computerhope** [Ray-Adams/NitroType-API-Docs#1]
Does NitroType still give access to the API? All my attempts to access any of these return a 404 error. It seems the only API I can now access is the leaderboards at: https://www.nitrotype.com/api/v2/leaderboards.

**Comment by Ray-Adams** [comment]
Hi @Computerhope, thanks for your inquiry!

It seems to me that the developers were in the process of tidying up their API when I made this repository. In the meantime, try adding `/v2/` before the endpoint if it's returning 404 (which should fix several errors).

**Please note:** After I update the documentation once more, the repo will be archived and no longer maintained.

**Comment by Ray-Adams** [comment]
**Also**: This repository will be moved to https://github.com/Ray-Adams/NitroType-Archive

**Comment by Ray-Adams** [comment]
@Computerhope @Barnac1ed I've fully updated the docs and added some related scripts (e.g. an endpoint scraper) here: https://github.com/Ray-Adams/NitroType-Archive/tree/master/API-Documentation
